import type { Metadata } from "next"
import { blogImageForPost } from "@/lib/blog-utils"
import { registerPageJsonLd } from "@/lib/json-ld-store"
import type { StoreProduct } from "@/lib/medusa"
import { productPath } from "@/lib/compound-product"
import { normalizeTb500DisplayText } from "@/lib/revamp/product-visual"
import { getProductPriceRangeCents } from "@/lib/product-price"
import {
  buildOgImagePath,
  isAllowedOgPhoto,
  OG_IMAGE_HEIGHT,
  OG_IMAGE_PATH,
  OG_IMAGE_TYPE,
  OG_IMAGE_WIDTH
} from "@/lib/og"
import {
  ORGANIZATION_ID,
  WEBSITE_ID,
  merchantOfferFields,
  merchantReturnPolicyJsonLd,
  shippingServiceJsonLd
} from "@/lib/merchant-listing-schema"
import { resolveSocialProfileUrls } from "@/lib/social-profiles"

const SITE_URL = (process.env.NEXT_PUBLIC_SITE_URL || "https://tetravalabs.com").replace(/\/$/, "")

/** Soft SERP budget; product titles use progressive fallbacks under this cap. */
export const META_TITLE_MAX = 70
export const META_DESCRIPTION_MAX = 160

/** Indexable pages: allow full snippets and large image previews (Discover / rich SERP). */
export const INDEXABLE_ROBOTS = {
  index: true,
  follow: true,
  googleBot: {
    index: true,
    follow: true,
    "max-snippet": -1,
    "max-image-preview": "large" as const,
    "max-video-preview": -1
  }
}

export const NOINDEX_ROBOTS = {
  index: false,
  follow: false
}

export type JsonLdGraph = Record<string, unknown>

export const siteConfig = {
  name: "Tetrava Labs",
  /** Short brand used in document `<title>` suffixes (`| Tetrava`). */
  titleBrand: "Tetrava",
  legalName: "Tetrava Labs",
  url: SITE_URL,
  description:
    "Research-use peptides with HPLC-MS verification, lot-linked COAs, and cold-chain shipping for qualified laboratories.",
  tagline: "Verified. Documented. Delivered.",
  locale: "en_US",
  twitterHandle: "@tetravalabs",
  contactEmail: "info@tetravalabs.com",
  /** Square mark for favicon, apple-touch, and Organization.logo. Not a social card. */
  logo: "/brand/tetravalabs-icon.png",
  /** 1200×630 fallback generated by `/og`. Per-page cards are built in `buildPageMetadata`. */
  defaultOgImage: OG_IMAGE_PATH,
  keywords: [
    "buy peptides online",
    "research peptides",
    "RUO peptides",
    "certificate of analysis",
    "HPLC peptide purity",
    "semaglutide research",
    "BPC-157 research",
    "peptide COA library"
  ]
}

type PageMetaInput = {
  title: string
  /** Bypasses the layout title template when an exact SERP title is required. */
  absoluteTitle?: string
  description?: string
  path?: string
  noIndex?: boolean
  type?: "website" | "article"
  publishedTime?: string
  /** Optional product/article photo composited onto the 1200×630 OG card. */
  image?: string
  /** Large heading on the OG card. Defaults to the page title without the brand suffix. */
  ogTitle?: string
  ogEyebrow?: string
  ogKicker?: string
  /** Page-specific keywords. Falls back to site defaults. */
  keywords?: string[]
  /** HTML `author` meta. Required for article SEO checkers. */
  authors?: Array<{ name: string; url?: string }>
  /** HTML `publisher` meta. Required for article SEO checkers. */
  publisher?: string
  /** Extra schema.org graphs for this route (registered for `<head>` injection). */
  jsonLd?: JsonLdGraph | JsonLdGraph[]
  /** Schema.org page type for auto-registered WebPage graph. */
  pageType?: "WebPage" | "CollectionPage" | "AboutPage" | "ContactPage"
  /** When true (default), auto-register a WebPage graph for `path`. */
  registerWebPage?: boolean
}

export function pageUrl(path = "") {
  if (!path || path === "/") return siteConfig.url
  return `${siteConfig.url}${path.startsWith("/") ? path : `/${path}`}`
}

const DATE_ONLY = /^\d{4}-\d{2}-\d{2}$/

/**
 * Schema.org datetime: ISO 8601 with timezone.
 * Date-only strings (`2026-08-17`) become midnight UTC so Google does not flag them.
 */
export function toSchemaDateTime(value?: string | null): string | undefined {
  const trimmed = value?.trim()
  if (!trimmed) return undefined
  if (DATE_ONLY.test(trimmed)) return `${trimmed}T00:00:00.000Z`
  const parsed = new Date(trimmed)
  if (Number.isNaN(parsed.getTime())) return undefined
  return parsed.toISOString()
}

/** Canonical Person URL when no dedicated author profile exists. */
export const DEFAULT_AUTHOR_PATH = "/about"

export type SchemaPersonInput = {
  name: string
  jobTitle?: string
  description?: string
  image?: string
  credentials?: string
  url?: string
}

function schemaPersonUrl(url?: string) {
  if (!url) return pageUrl(DEFAULT_AUTHOR_PATH)
  if (/^https?:\/\//i.test(url)) return url
  return pageUrl(url)
}

const BRAND_SUFFIX = ` | ${siteConfig.titleBrand}`

/** Drop trailing separators left by length clamps (avoids "Name — | Brand"). */
function stripTrailingTitleSeparators(text: string) {
  return text.replace(/[\s|/\\•·–—-]+$/g, "").trim()
}

function truncateMetaText(text: string, max: number) {
  const normalized = text.replace(/\s+/g, " ").trim()
  if (normalized.length <= max) return normalized

  const slice = normalized.slice(0, max)
  const lastSpace = slice.lastIndexOf(" ")
  const clipped =
    lastSpace >= Math.floor(max * 0.5) ? slice.slice(0, lastSpace).trim() : slice.trim()

  return stripTrailingTitleSeparators(clipped)
}

export function clampMetaDescription(description: string) {
  return truncateMetaText(description, META_DESCRIPTION_MAX)
}

/** Strip trailing `| Tetrava` / `| Tetrava Labs` brand suffixes from titles. */
export function stripBrandTitleSuffix(title: string) {
  return title.replace(/\s*\|\s*Tetrava(?:\s+Labs)?\s*$/i, "").trim()
}

export function resolveMetaTitles(input: { title: string; absoluteTitle?: string }) {
  if (input.absoluteTitle) {
    const absolute = truncateMetaText(input.absoluteTitle.trim(), META_TITLE_MAX)
    return {
      documentTitle: { absolute } as Metadata["title"],
      shortTitle: absolute,
      fullTitle: absolute
    }
  }

  let shortTitle = stripBrandTitleSuffix(input.title)

  if (shortTitle.includes(siteConfig.name)) {
    const absolute = truncateMetaText(shortTitle, META_TITLE_MAX)
    return {
      documentTitle: { absolute } as Metadata["title"],
      shortTitle: absolute,
      fullTitle: absolute
    }
  }

  const maxShort = META_TITLE_MAX - BRAND_SUFFIX.length
  shortTitle = truncateMetaText(shortTitle, maxShort)
  const fullTitle = truncateMetaText(`${shortTitle}${BRAND_SUFFIX}`, META_TITLE_MAX)

  return {
    documentTitle: shortTitle,
    shortTitle,
    fullTitle
  }
}

export function buildPageMetadata(input: PageMetaInput): Metadata {
  const { documentTitle, shortTitle, fullTitle } = resolveMetaTitles({
    title: input.title,
    absoluteTitle: input.absoluteTitle
  })
  const description = clampMetaDescription(input.description || siteConfig.description)
  const url = pageUrl(input.path)
  const ogTitle = input.ogTitle || stripBrandTitleSuffix(shortTitle)
  const ogImage = pageUrl(
    buildOgImagePath({
      title: ogTitle,
      eyebrow: input.ogEyebrow,
      kicker: input.ogKicker || (input.type === "article" ? "Research Hub" : siteConfig.tagline),
      photo: isAllowedOgPhoto(input.image) ? input.image : undefined
    })
  )

  if (input.path && !input.noIndex) {
    const graphs: JsonLdGraph[] = []
    if (input.registerWebPage !== false) {
      const pageType =
        input.pageType ||
        (input.path === "/shop" || input.path === "/categories" || input.path === "/blog" || input.path === "/coa-library"
          ? "CollectionPage"
          : input.path === "/contact"
            ? "ContactPage"
            : "WebPage")
      graphs.push(
        webPageJsonLd({
          title: shortTitle,
          description,
          path: input.path,
          type: pageType
        })
      )
    }
    if (input.jsonLd) {
      graphs.push(...(Array.isArray(input.jsonLd) ? input.jsonLd : [input.jsonLd]))
    }
    registerPageJsonLd(input.path, graphs)
  }

  const isArticle = input.type === "article"
  const authors =
    input.authors && input.authors.length > 0
      ? input.authors
      : isArticle
        ? [{ name: siteConfig.name }]
        : undefined
  const publisher = input.publisher || (isArticle ? siteConfig.name : undefined)

  return {
    title: documentTitle,
    description,
    keywords: input.keywords?.length ? input.keywords : siteConfig.keywords,
    ...(authors ? { authors } : {}),
    ...(publisher ? { publisher } : {}),
    alternates: { canonical: url },
    robots: input.noIndex ? NOINDEX_ROBOTS : INDEXABLE_ROBOTS,
    openGraph: {
      title: fullTitle,
      description,
      url,
      siteName: siteConfig.name,
      locale: siteConfig.locale,
      type: input.type || "website",
      images: [
        {
          url: ogImage,
          width: OG_IMAGE_WIDTH,
          height: OG_IMAGE_HEIGHT,
          type: OG_IMAGE_TYPE,
          alt: ogTitle
        }
      ],
      ...(input.publishedTime ? { publishedTime: input.publishedTime } : {}),
      ...(isArticle && authors
        ? { authors: authors.map((author) => author.name) }
        : {})
    },
    twitter: {
      card: "summary_large_image",
      title: fullTitle,
      description,
      images: [
        {
          url: ogImage,
          width: OG_IMAGE_WIDTH,
          height: OG_IMAGE_HEIGHT,
          alt: ogTitle
        }
      ],
      ...(siteConfig.twitterHandle ? { site: siteConfig.twitterHandle } : {})
    }
  }
}

export function breadcrumbJsonLd(items: Array<{ label: string; href?: string }>) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((item, index) => {
      const isLast = index === items.length - 1
      return {
        "@type": "ListItem",
        position: index + 1,
        name: item.label,
        ...(item.href && !isLast ? { item: pageUrl(item.href) } : {})
      }
    })
  }
}

/** Person schema for a content author's byline (E-E-A-T authorship signal). */
export function personJsonLd(author: SchemaPersonInput) {
  const graph: JsonLdGraph = {
    "@type": "Person",
    name: author.name,
    url: schemaPersonUrl(author.url),
    worksFor: { "@id": ORGANIZATION_ID }
  }
  if (author.jobTitle) graph.jobTitle = author.jobTitle
  if (author.description) graph.description = author.description
  if (author.image) {
    graph.image = author.image.startsWith("http") ? author.image : pageUrl(author.image)
  }
  if (author.credentials) graph.honorificSuffix = author.credentials
  return graph
}

function organizationLogoJsonLd() {
  return {
    "@type": "ImageObject",
    url: pageUrl(siteConfig.logo),
    contentUrl: pageUrl(siteConfig.logo)
  }
}

/** Organization publisher block (name + logo) — required by most Article SEO checkers. */
export function publisherJsonLd() {
  return {
    "@id": ORGANIZATION_ID,
    "@type": "Organization",
    name: siteConfig.name,
    url: siteConfig.url,
    logo: organizationLogoJsonLd()
  }
}

/** Fallback author when a page has no named byline (still satisfies Author schema checks). */
export function defaultPageAuthorJsonLd() {
  return {
    "@id": ORGANIZATION_ID,
    "@type": "Organization",
    name: siteConfig.name,
    url: siteConfig.url
  }
}

export function webPageJsonLd(input: {
  title: string
  description?: string
  path: string
  type?: "WebPage" | "CollectionPage" | "AboutPage" | "ContactPage"
  /** Byline author, when the page has curated editorial/research content. */
  author?: SchemaPersonInput
  /** Primary entity this page is about (Organization, Product, Article). */
  mainEntity?: JsonLdGraph
}) {
  const url = pageUrl(input.path)
  const pageType = input.type || "WebPage"
  const graph: JsonLdGraph = {
    "@context": "https://schema.org",
    "@type": pageType,
    "@id": url,
    name: input.title,
    description: input.description || siteConfig.description,
    url,
    inLanguage: "en-US",
    isPartOf: { "@id": WEBSITE_ID },
    publisher: publisherJsonLd(),
    author: input.author ? personJsonLd(input.author) : defaultPageAuthorJsonLd()
  }

  if (input.mainEntity) {
    graph.mainEntity = input.mainEntity
  } else if (pageType === "AboutPage" || input.path === "/") {
    graph.mainEntity = { "@id": ORGANIZATION_ID }
    graph.about = { "@id": ORGANIZATION_ID }
  } else if (pageType === "ContactPage") {
    graph.mainEntity = {
      "@type": "ContactPoint",
      contactType: "customer support",
      email: siteConfig.contactEmail
    }
  }

  return graph
}

type ProductLike = {
  title: string
  handle: string
  description?: string | null
  variants?: Array<{
    id: string
    sku?: string | null
    prices?: Array<{ amount: number }>
    calculated_price?: { calculated_amount?: number }
    inventory_quantity?: number | null
    manage_inventory?: boolean | null
    allow_backorder?: boolean | null
  }>
  metadata?: Record<string, unknown> | null
}

function productPriceRange(product: ProductLike) {
  const { min, max } = getProductPriceRangeCents(product as StoreProduct)
  return { low: min / 100, high: max / 100 }
}

function isProductLikeVariantInStock(
  variant: NonNullable<ProductLike["variants"]>[number] | undefined
): boolean {
  if (!variant) return false
  if (variant.manage_inventory === false) return true
  if (variant.allow_backorder) return true
  if (variant.inventory_quantity == null) return true
  return variant.inventory_quantity > 0
}

function productAvailability(product: ProductLike) {
  const variants = product.variants || []
  if (!variants.length) return "https://schema.org/OutOfStock"
  return variants.some((variant) => isProductLikeVariantInStock(variant))
    ? "https://schema.org/InStock"
    : "https://schema.org/OutOfStock"
}

export type ProductReviewSchemaInput = {
  ratingValue: number
  reviewCount: number
  reviews?: Array<{
    authorName: string
    rating: number
    body: string
    datePublished?: string
  }>
}

export type ProductOfferVariantInput = {
  name: string
  sku?: string | null
  priceUsd: number
  inStock: boolean
  /** Strength × pack label (ProductGroup variesBy size). */
  size?: string | null
}

function offerAvailability(inStock: boolean) {
  return inStock ? "https://schema.org/InStock" : "https://schema.org/OutOfStock"
}

function offerSizeLabel(input: ProductOfferVariantInput) {
  const explicit = input.size?.trim()
  if (explicit) return explicit
  const parts = input.name.split(" · ").map((part) => part.trim()).filter(Boolean)
  return parts.length > 1 ? parts.slice(1).join(" · ") : input.name
}

function schemaOfferNode(input: ProductOfferVariantInput, productUrl: string) {
  return {
    "@type": "Offer",
    name: input.name,
    url: productUrl,
    priceCurrency: "USD",
    price: input.priceUsd.toFixed(2),
    availability: offerAvailability(input.inStock),
    itemCondition: "https://schema.org/NewCondition",
    seller: {
      "@id": ORGANIZATION_ID,
      "@type": "Organization",
      name: siteConfig.name
    },
    ...merchantOfferFields()
  } satisfies JsonLdGraph
}

function schemaOffers(
  product: ProductLike,
  productUrl: string,
  variantOffers?: ProductOfferVariantInput[]
) {
  const explicit = (variantOffers || []).filter((offer) => offer.priceUsd > 0)
  if (explicit.length === 1) return schemaOfferNode(explicit[0], productUrl)
  if (explicit.length > 1) return explicit.map((offer) => schemaOfferNode(offer, productUrl))

  const { low, high } = productPriceRange(product)
  const offerPrice = low || high
  const availability = productAvailability(product)
  const hasRange = Boolean(low && high && low !== high)
  if (hasRange) {
    return {
      "@type": "AggregateOffer",
      url: productUrl,
      priceCurrency: "USD",
      lowPrice: low.toFixed(2),
      highPrice: high.toFixed(2),
      offerCount: product.variants?.length || 1,
      availability,
      itemCondition: "https://schema.org/NewCondition",
      ...merchantOfferFields()
    }
  }
  return {
    "@type": "Offer",
    url: productUrl,
    priceCurrency: "USD",
    price: offerPrice ? offerPrice.toFixed(2) : undefined,
    availability,
    itemCondition: "https://schema.org/NewCondition",
    ...merchantOfferFields()
  }
}

function attachProductReviews(graph: JsonLdGraph, reviewData?: ProductReviewSchemaInput | null) {
  if (!reviewData || reviewData.reviewCount <= 0 || reviewData.ratingValue <= 0) return graph

  graph.aggregateRating = {
    "@type": "AggregateRating",
    ratingValue: Number(reviewData.ratingValue.toFixed(1)),
    reviewCount: reviewData.reviewCount,
    bestRating: 5,
    worstRating: 1
  }

  const nested = (reviewData.reviews || [])
    .filter((item) => item.rating > 0 && item.body.trim())
    .slice(0, 6)
    .map((item) => {
      const datePublished = toSchemaDateTime(item.datePublished)
      return {
        "@type": "Review",
        author: {
          "@type": "Person",
          name: item.authorName.trim() || "Verified buyer"
        },
        reviewRating: {
          "@type": "Rating",
          ratingValue: item.rating,
          bestRating: 5,
          worstRating: 1
        },
        reviewBody: item.body.trim(),
        ...(datePublished ? { datePublished } : {})
      }
    })

  if (nested.length) graph.review = nested
  return graph
}

export function productJsonLd(
  product: ProductLike,
  handle: string,
  imagePath?: string,
  reviewData?: ProductReviewSchemaInput | null,
  variantOffers?: ProductOfferVariantInput[]
) {
  const displayTitle = normalizeTb500DisplayText(product.title)
  const categoryLabel = normalizeTb500DisplayText(
    String(product.metadata?.source_category || "Research Product")
  )
  const image = imagePath || `/products/${handle}.jpg`
  const imageUrl = image.startsWith("http") ? image : pageUrl(image)
  const sku =
    variantOffers?.find((offer) => offer.sku)?.sku ||
    product.variants?.find((variant) => variant.sku)?.sku ||
    product.variants?.[0]?.id
  const description = normalizeTb500DisplayText(
    (typeof product.description === "string" && product.description.trim()) ||
      `${displayTitle} — research-use only (RUO) peptide with HPLC-MS verification.`
  )
  const productUrl = pageUrl(productPath(handle))
  const productId = `${productUrl}#product`
  const pricedOffers = (variantOffers || []).filter((offer) => offer.priceUsd > 0)
  const brand = { "@type": "Brand", name: "Tetrava Labs" }
  const images = [imageUrl]

  if (pricedOffers.length > 1) {
    return attachProductReviews(
      {
        "@context": "https://schema.org/",
        "@type": "ProductGroup",
        "@id": productId,
        name: displayTitle,
        description,
        url: productUrl,
        image: images,
        category: categoryLabel,
        brand,
        productGroupID: handle,
        variesBy: ["https://schema.org/size"],
        hasVariant: pricedOffers.map((offer) => {
          const size = offerSizeLabel(offer)
          const skuValue = offer.sku || undefined
          return {
            "@type": "Product",
            ...(skuValue ? { "@id": `${productUrl}#${skuValue}` } : {}),
            name: offer.name,
            description,
            url: productUrl,
            image: images,
            brand,
            size,
            inProductGroupWithID: handle,
            ...(skuValue ? { sku: skuValue, mpn: skuValue } : {}),
            offers: schemaOfferNode(offer, productUrl)
          }
        })
      },
      reviewData
    )
  }

  const size = pricedOffers[0] ? offerSizeLabel(pricedOffers[0]) : undefined
  const graph: JsonLdGraph = {
    "@context": "https://schema.org/",
    "@type": "Product",
    "@id": productId,
    name: displayTitle,
    description,
    url: productUrl,
    image: images,
    sku,
    ...(sku ? { mpn: sku } : {}),
    ...(size ? { size } : {}),
    category: categoryLabel,
    brand,
    offers: schemaOffers(product, productUrl, variantOffers)
  }

  return attachProductReviews(graph, reviewData)
}

export function articleJsonLd(post: {
  title: string
  slug: string
  excerpt?: string
  seoDescription?: string
  publishedAt?: string
  updatedAt?: string
  category?: string
  image?: string
  author?: SchemaPersonInput
}) {
  const imagePath = blogImageForPost({
    image: post.image,
    category: post.category as "Protocols" | "Analytical" | "Compliance" | undefined
  })
  const datePublished = toSchemaDateTime(post.publishedAt)
  const dateModified = toSchemaDateTime(post.updatedAt || post.publishedAt)
  const url = pageUrl(`/blog/${post.slug}`)
  const imageUrl = imagePath.startsWith("http") ? imagePath : pageUrl(imagePath)

  return {
    "@context": "https://schema.org",
    "@type": "Article",
    "@id": `${url}#article`,
    headline: post.title,
    description: post.seoDescription || post.excerpt,
    url,
    inLanguage: "en-US",
    ...(post.category ? { articleSection: post.category } : {}),
    ...(datePublished ? { datePublished } : {}),
    ...(dateModified ? { dateModified } : {}),
    image: [imageUrl],
    author: post.author ? personJsonLd(post.author) : defaultPageAuthorJsonLd(),
    publisher: publisherJsonLd(),
    mainEntityOfPage: { "@type": "WebPage", "@id": url }
  }
}

/** VideoObject for a dedicated watch page only. Do not emit on Research Hub articles. */
export function videoObjectJsonLd(input: {
  name: string
  description: string
  youtubeId: string
  path: string
  /** ISO 8601 upload date; required by Google VideoObject rich results. */
  uploadDate?: string
  thumbnail?: string
}) {
  const embedUrl = `https://www.youtube-nocookie.com/embed/${input.youtubeId}`
  const thumbnailUrl = input.thumbnail || `https://i.ytimg.com/vi/${input.youtubeId}/maxresdefault.jpg`
  const uploadDate = resolveVideoUploadDate(input.uploadDate)

  return {
    "@context": "https://schema.org",
    "@type": "VideoObject",
    name: input.name,
    description: input.description,
    thumbnailUrl,
    uploadDate,
    embedUrl,
    contentUrl: `https://www.youtube.com/watch?v=${input.youtubeId}`,
    isPartOf: pageUrl(input.path)
  }
}

/** Google requires VideoObject.uploadDate — normalize or fall back to a stable ISO date. */
export function resolveVideoUploadDate(...candidates: Array<string | undefined | null>) {
  for (const value of candidates) {
    const iso = toSchemaDateTime(value)
    if (iso) return iso
  }
  return "2026-01-01T00:00:00.000Z"
}

/** Article graph for curated product research PDPs (author + publisher for SEO checkers). */
export function productResearchArticleJsonLd(input: {
  headline: string
  description: string
  path: string
  image?: string
  datePublished?: string
  dateModified?: string
  author: SchemaPersonInput
}) {
  const datePublished = toSchemaDateTime(input.datePublished)
  const dateModified = toSchemaDateTime(input.dateModified)
  const url = pageUrl(input.path)
  return {
    "@context": "https://schema.org",
    "@type": "Article",
    "@id": `${url}#article`,
    headline: input.headline,
    description: input.description,
    url,
    inLanguage: "en-US",
    articleSection: "Research",
    mainEntityOfPage: { "@type": "WebPage", "@id": url },
    ...(input.image
      ? { image: [input.image.startsWith("http") ? input.image : pageUrl(input.image)] }
      : {}),
    ...(datePublished ? { datePublished } : {}),
    ...(dateModified ? { dateModified } : {}),
    author: personJsonLd(input.author),
    publisher: publisherJsonLd()
  }
}

export function organizationJsonLd() {
  const sameAs = resolveSocialProfileUrls()
  return {
    "@context": "https://schema.org",
    "@type": "OnlineStore",
    "@id": ORGANIZATION_ID,
    name: siteConfig.name,
    alternateName: siteConfig.titleBrand,
    legalName: siteConfig.legalName,
    url: siteConfig.url,
    logo: organizationLogoJsonLd(),
    email: siteConfig.contactEmail,
    description: siteConfig.description,
    areaServed: "Worldwide",
    contactPoint: {
      "@type": "ContactPoint",
      contactType: "customer support",
      email: siteConfig.contactEmail,
      areaServed: "Worldwide"
    },
    hasMerchantReturnPolicy: merchantReturnPolicyJsonLd(),
    hasShippingService: shippingServiceJsonLd(),
    ...(sameAs.length ? { sameAs } : {})
  }
}

export function websiteJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "WebSite",
    "@id": WEBSITE_ID,
    name: siteConfig.name,
    alternateName: siteConfig.titleBrand,
    url: siteConfig.url,
    description: siteConfig.description,
    inLanguage: "en-US",
    publisher: { "@id": ORGANIZATION_ID },
    potentialAction: {
      "@type": "SearchAction",
      target: {
        "@type": "EntryPoint",
        urlTemplate: `${siteConfig.url}/search?q={search_term_string}`
      },
      "query-input": "required name=search_term_string"
    }
  }
}
